from api.util.http import QueryParam

class GetSongsQueryParams(QueryParam):
  ALBUM_ID    = 'album_id',    False, int, 'an integer', None, 'the id of the album whose songs to get; only one of this and album_name can be set.'
  ALBUM_NAME  = 'album_name',  False, str, 'a string',   None, 'the name of the album whose songs to get; only one of this and album_id can be set.'
  ALBUM_NAME_IS_AN_EXACT_MATCH = 'album_name_is_an_exact_match', False, bool, 'a boolean', None, 'if album_name isn\'t set, album_name_is_an_exact_match is ignored.  if album_name_is_an_exact_match is true, only songs whose album\'s name is exactly equal to album_name will be returned; otherwise, songs whose album\'s name contains album_name will be returned.'
  ALBUM_ARTIST_ID = 'album_artist_id',      False, int, 'an integer', None, 'the id of the artist who wrote the album whose songs to get; only one of this and album_artist_name can be set.  if neither of album_id and album_name are set, this will be ignored.'
  ALBUM_ARTIST_NAME = 'album_artist_name',  False, str, 'a string',   None, 'the name of the artist who wrote the album whose songs to get; only one of this and album_artist_id can be set.  if neither of album_id and album_name are set, this will be ignored.'
  ALBUM_ARTIST_NAME_IS_AN_EXACT_MATCH = 'album_artist_name_is_an_exact_match', False, bool, 'a boolean', None, 'if album_artist_name isn\'t set, album_artist_name_is_an_exact_match is ignored.  if album_artist_name_is_an_exact_match is true, only songs whose album artist\'s name is exactly equal to album_artist_name will be returned; otherwise, songs whose album artist\'s name contains album_artist_name will be returned.'
  ARTIST_ID   = 'artist_id',   False, int, 'an integer', None, 'the id of the artist whose songs to get; only one of this and artist_name can be set.'
  ARTIST_NAME = 'artist_name', False, str, 'a string',   None, 'the name of the artist whose songs to get; only one of this and artist_id can be set.'
  ARTIST_NAME_IS_AN_EXACT_MATCH = 'artist_name_is_an_exact_match', False, bool, 'a boolean', None, 'if artist_name isn\'t set, artist_name_is_an_exact_match is ignored.  if artist_name_is_an_exact_match is true, only songs whose artist\'s name is exactly equal to artist_name will be returned; otherwise, songs whose artist\'s name contains artist_name will be returned.'
  CATALOG_ID  = 'catalog_id',  True,  int, 'an integer', None, 'the id of the catalog to retrieve songs from'
  GENRE_ID    = 'genre_id',    False, int, 'an integer', None, 'the id of the genre whose songs to get; only one of this and genre_name can be set.'
  GENRE_NAME  = 'genre_name',  False, str, 'a string',   None, 'the name of the genre whose songs to get; only one of this and genre_id can be set.'
  GENRE_NAME_IS_AN_EXACT_MATCH = 'genre_name_is_an_exact_match', False, bool, 'a boolean', None, 'if genre_name isn\'t set, genre_name_is_an_exact_match is ignored.  if genre_name_is_an_exact_match is true, only songs whose genre\'s name is exactly equal to genre_name will be returned; otherwise, songs whose genre\'s name contains genre_name will be returned.'
  SONG_NAME   = 'song_name',   False, str, 'a string',   None, 'the name of the songs to get'
  SONG_NAME_IS_AN_EXACT_MATCH = 'song_name_is_an_exact_match', False, bool, 'a boolean', None, 'if song_name isn\'t set, song_name_is_an_exact_match is ignored.  if song_name_is_an_exact_match is true, only songs whose name is exactly equal to song_name will be returned; otherwise, songs whose name contains song_name will be returned.'
  SONG_YEAR   = 'song_year',   False, int, 'an integer', None, 'the year of the songs to get'